version: "3.8"

services:

#  nginx:
#    image: nginx:1.21-alpine
#    ports:
#      - "8088:80"
#    volumes:
#      - ./config/server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./:/var/www/html:ro
#    depends_on:
#      - php

  php:
    build:
      dockerfile: ./config/server/php.dockerfile
    user: "1000:1000" # некрасиво, но для тестовой версии пойдёт
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html:rw
    entrypoint: ['php', '-S', '0.0.0.0:80', '-t', '/var/www/html/public']
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:
